# Configurations for the model
# ----------------------------
# input_dim and output_dim will be set by the dataset
# it will be the same as gym.yaml -> sensory.num
hidden_dim: 1000
activation: relu
alpha: 0.1 # Decay time constant, the \gamma in the paper
biases: null
preact_noise: 0
postact_noise: 0
suppress_warnings: true
lr: 0.0005
optimizer: adam